import type { Metadata } from "next";
import { Radio_Canada } from "next/font/google";
import "./globals.css";

const font = Radio_Canada({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Know Ball",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
